package com.eco4ndly.morse_translater.core

/**
 * A Sayan Porya code on 23/04/20
 */
object MorseMap {
    fun englishToMorse(toEncode: String): String {
        if (toEncode == " ") return " / "
        //if (toEncode == "") return "|"
        if (toEncode.equals("a", ignoreCase = true)) return ".-"
        if (toEncode.equals("b", ignoreCase = true)) return "-..."
        if (toEncode.equals("c", ignoreCase = true)) return "-.-."
        if (toEncode.equals("d", ignoreCase = true)) return "-.."
        if (toEncode.equals("e", ignoreCase = true)) return "."
        if (toEncode.equals("f", ignoreCase = true)) return "..-."
        if (toEncode.equals("g", ignoreCase = true)) return "--."
        if (toEncode.equals("h", ignoreCase = true)) return "...."
        if (toEncode.equals("i", ignoreCase = true)) return ".."
        if (toEncode.equals("j", ignoreCase = true)) return ".---"
        if (toEncode.equals("k", ignoreCase = true)) return "-.-"
        if (toEncode.equals("l", ignoreCase = true)) return ".-.."
        if (toEncode.equals("m", ignoreCase = true)) return "--"
        if (toEncode.equals("n", ignoreCase = true)) return "-."
        if (toEncode.equals("o", ignoreCase = true)) return "---"
        if (toEncode.equals("p", ignoreCase = true)) return ".--."
        if (toEncode.equals("q", ignoreCase = true)) return "--.-"
        if (toEncode.equals("r", ignoreCase = true)) return ".-."
        if (toEncode.equals("s", ignoreCase = true)) return "..."
        if (toEncode.equals("t", ignoreCase = true)) return "-"
        if (toEncode.equals("u", ignoreCase = true)) return "..-"
        if (toEncode.equals("v", ignoreCase = true)) return "...-"
        if (toEncode.equals("w", ignoreCase = true)) return ".--"
        if (toEncode.equals("x", ignoreCase = true)) return "-..-"
        if (toEncode.equals("y", ignoreCase = true)) return "-.--"
        if (toEncode.equals("z", ignoreCase = true)) return "--.."
        if (toEncode.equals("0", ignoreCase = true)) return "-----"
        if (toEncode.equals("1", ignoreCase = true)) return ".----"
        if (toEncode.equals("2", ignoreCase = true)) return "..---"
        if (toEncode.equals("3", ignoreCase = true)) return "...--"
        if (toEncode.equals("4", ignoreCase = true)) return "....-"
        if (toEncode.equals("5", ignoreCase = true)) return "....."
        if (toEncode.equals("6", ignoreCase = true)) return "-...."
        if (toEncode.equals("7", ignoreCase = true)) return "--..."
        if (toEncode.equals("8", ignoreCase = true)) return "---.."
        if (toEncode.equals("9", ignoreCase = true)) return "----."
        if (toEncode.equals(".", ignoreCase = true)) return ".-.-"
        if (toEncode.equals(",", ignoreCase = true)) return "--..--"
        if (toEncode.equals("?", ignoreCase = true)) return "..--.."
        return ""
    }

    fun morseToEnglish(toEncode: String): String? {
        if (toEncode == ".-") return "a"
        if (toEncode == "-...") return "b"
        if (toEncode == "-.-.") return "c"
        if (toEncode == "-..") return "d"
        if (toEncode == ".") return "e"
        if (toEncode == "..-.") return "f"
        if (toEncode == "--.") return "g"
        if (toEncode == "....") return "h"
        if (toEncode == "..") return "i"
        if (toEncode == ".---") return "j"
        if (toEncode == "-.-") return "k"
        if (toEncode == ".-..") return "l"
        if (toEncode == "--") return "m"
        if (toEncode == "-.") return "n"
        if (toEncode == "---") return "o"
        if (toEncode == ".--.") return "p"
        if (toEncode == "--.-") return "q"
        if (toEncode == ".-.") return "r"
        if (toEncode == "...") return "s"
        if (toEncode == "-") return "t"
        if (toEncode == "..-") return "u"
        if (toEncode == "...-") return "v"
        if (toEncode == ".--") return "w"
        if (toEncode == "-..-") return "x"
        if (toEncode == "-.--") return "y"
        if (toEncode == "--..") return "z"
        if (toEncode == "-----") return "0"
        if (toEncode == ".----") return "1"
        if (toEncode == "..---") return "2"
        if (toEncode == "...--") return "3"
        if (toEncode == "....-") return "4"
        if (toEncode == ".....") return "5"
        if (toEncode == "-....") return "6"
        if (toEncode == "--...") return "7"
        if (toEncode == "---..") return "8"
        if (toEncode == "----.") return "9"
        if (toEncode == "|") return ""
        if (toEncode == "/") return " "
        if (toEncode == " ") return " "
        return ""
    }
}